databases:
  - name: django-game-soccer
    databaseName: django_game_soccer
    user: django_game_soccer_user

services:
  - type: web
    name: project
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn project.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django-game-soccer
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4